services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

# networks:
#   sharepro-network:
#     external: true
