services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--max-old-space-size=4096
    volumes:
      # Mount source code for hot reloading
      - .:/app
      # Use named volumes for better performance and permission handling
      - node_modules:/app/node_modules
      - next_cache:/app/.next
      # Optionally exclude .git to improve performance
      - /app/.git
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  node_modules:
  next_cache:

# networks:
#   sharepro-network:
#     external: true
